#基本配置
server:
  port: 0 #项目使用的端口号

cookie_name: authentication

spring:
  #配置数据库
  datasource:
    url: jdbc:sqlite:extra/db/pin_duo_duo.db #数据库的url
    username: root #数据库的username
    password: "root" #数据库的password
    driver-class-name: org.sqlite.JDBC #数据库所使用的驱动
  #配置Spring Data Jpa
  jpa:
    show-sql: true #显示自动生成或自己书写的SQL语句
    #设置Sqlite方言
    database-platform: com.eks.utils.SQLiteDialect
    hibernate:
      #[reate：表示启动的时候先drop，再create][create-drop: 也表示创建，只不过再系统关闭前执行一下drop][update: 这个操作启动的时候会去检查schema是否一致，如果不一致会做scheme更新][validate: 启动时验证现有schema与你配置的hibernate是否一致，如果不一致就抛出异常，并不做更新]
      ddl-auto: update